# Generated by Django 5.1 on 2024-08-27 14:49

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(default='50030', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_address',
            field=models.CharField(default='Rajendranagar', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Hyderabad', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, default='TS', max_length=100, null=True),
        ),
    ]
